import { Course, Category, SubCategory } from '@/types/course';

export const categories: Category[] = [
  {
    id: '1',
    name: 'Web Development',
    icon: '💻',
    courseCount: 245,
    subCategories: [
      { id: '1-1', name: 'React', courseCount: 85, icon: '⚛️' },
      { id: '1-2', name: 'Vue.js', courseCount: 42, icon: '🟢' },
      { id: '1-3', name: 'Angular', courseCount: 38, icon: '🔴' },
      { id: '1-4', name: 'Node.js', courseCount: 56, icon: '🟢' },
      { id: '1-5', name: 'Full Stack', courseCount: 24, icon: '🔗' },
    ],
  },
  {
    id: '2',
    name: 'Data Science',
    icon: '📊',
    courseCount: 189,
    subCategories: [
      { id: '2-1', name: 'Python', courseCount: 72, icon: '🐍' },
      { id: '2-2', name: 'Machine Learning', courseCount: 45, icon: '🤖' },
      { id: '2-3', name: 'Data Analysis', courseCount: 38, icon: '📈' },
      { id: '2-4', name: 'Deep Learning', courseCount: 24, icon: '🧠' },
      { id: '2-5', name: 'R Programming', courseCount: 10, icon: '📊' },
    ],
  },
  {
    id: '3',
    name: 'Mobile Development',
    icon: '📱',
    courseCount: 156,
    subCategories: [
      { id: '3-1', name: 'iOS Development', courseCount: 48, icon: '🍎' },
      { id: '3-2', name: 'Android Development', courseCount: 52, icon: '🤖' },
      { id: '3-3', name: 'React Native', courseCount: 32, icon: '⚛️' },
      { id: '3-4', name: 'Flutter', courseCount: 18, icon: '💙' },
      { id: '3-5', name: 'Swift', courseCount: 6, icon: '🦉' },
    ],
  },
  {
    id: '4',
    name: 'Design',
    icon: '🎨',
    courseCount: 203,
    subCategories: [
      { id: '4-1', name: 'UI/UX Design', courseCount: 68, icon: '🎨' },
      { id: '4-2', name: 'Graphic Design', courseCount: 52, icon: '🖼️' },
      { id: '4-3', name: 'Web Design', courseCount: 45, icon: '🌐' },
      { id: '4-4', name: 'Figma', courseCount: 28, icon: '🎭' },
      { id: '4-5', name: 'Adobe XD', courseCount: 10, icon: '💜' },
    ],
  },
  {
    id: '5',
    name: 'Business',
    icon: '💼',
    courseCount: 178,
    subCategories: [
      { id: '5-1', name: 'Entrepreneurship', courseCount: 42, icon: '🚀' },
      { id: '5-2', name: 'Finance', courseCount: 38, icon: '💰' },
      { id: '5-3', name: 'Management', courseCount: 35, icon: '👔' },
      { id: '5-4', name: 'Leadership', courseCount: 28, icon: '👑' },
      { id: '5-5', name: 'Project Management', courseCount: 35, icon: '📋' },
    ],
  },
  {
    id: '6',
    name: 'Marketing',
    icon: '📈',
    courseCount: 134,
    subCategories: [
      { id: '6-1', name: 'Digital Marketing', courseCount: 48, icon: '📱' },
      { id: '6-2', name: 'SEO', courseCount: 32, icon: '🔍' },
      { id: '6-3', name: 'Social Media', courseCount: 28, icon: '📲' },
      { id: '6-4', name: 'Content Marketing', courseCount: 18, icon: '✍️' },
      { id: '6-5', name: 'Email Marketing', courseCount: 8, icon: '📧' },
    ],
  },
  {
    id: '7',
    name: 'Photography',
    icon: '📷',
    courseCount: 98,
    subCategories: [
      { id: '7-1', name: 'Portrait Photography', courseCount: 24, icon: '👤' },
      { id: '7-2', name: 'Landscape Photography', courseCount: 18, icon: '🏔️' },
      { id: '7-3', name: 'Photo Editing', courseCount: 28, icon: '🖼️' },
      { id: '7-4', name: 'Lightroom', courseCount: 15, icon: '💡' },
      { id: '7-5', name: 'Photoshop', courseCount: 13, icon: '🎨' },
    ],
  },
  {
    id: '8',
    name: 'Music',
    icon: '🎵',
    courseCount: 87,
    subCategories: [
      { id: '8-1', name: 'Music Production', courseCount: 32, icon: '🎹' },
      { id: '8-2', name: 'Guitar', courseCount: 18, icon: '🎸' },
      { id: '8-3', name: 'Piano', courseCount: 15, icon: '🎹' },
      { id: '8-4', name: 'Music Theory', courseCount: 12, icon: '🎼' },
      { id: '8-5', name: 'DJing', courseCount: 10, icon: '🎧' },
    ],
  },
];

export const courses: Course[] = [
  {
    id: '1',
    title: 'Complete React Development Bootcamp',
    instructor: 'John Smith',
    instructorImage: `https://i.pravatar.cc/40?img=1`,
    description: 'Master React from scratch. Build real-world projects and learn modern React patterns including hooks, context, and more.',
    shortDescription: 'Master React from scratch. Build real-world projects.',
    price: 89.99,
    originalPrice: 199.99,
    rating: 4.7,
    reviewCount: 1234,
    studentCount: 15420,
    image: `https://picsum.photos/400/250?random=1`,
    category: 'Web Development',
    subCategory: 'React',
    level: 'Intermediate',
    duration: '24.5 hours',
    language: 'English',
    lastUpdated: '2024-01-15',
    createdAt: '2023-12-01',
    whatYouWillLearn: [
      'Build modern React applications',
      'Understand React hooks and context',
      'Implement routing and state management',
      'Deploy React apps to production',
    ],
    requirements: [
      'Basic JavaScript knowledge',
      'HTML and CSS fundamentals',
      'A computer with internet connection',
    ],
    curriculum: [
      {
        id: '1',
        title: 'Getting Started',
        lectures: [
          { id: '1', title: 'Introduction to React', duration: '15:30', isPreview: true },
          { id: '2', title: 'Setting up your environment', duration: '12:45', isPreview: false },
        ],
      },
      {
        id: '2',
        title: 'React Fundamentals',
        lectures: [
          { id: '3', title: 'Components and Props', duration: '20:15', isPreview: false },
          { id: '4', title: 'State and Events', duration: '18:30', isPreview: true },
        ],
      },
    ],
    reviews: [
      {
        id: '1',
        userName: 'Alice Johnson',
        rating: 5,
        comment: 'Excellent course! Very comprehensive and well-structured.',
        date: '2024-01-10',
      },
      {
        id: '2',
        userName: 'Bob Williams',
        rating: 4,
        comment: 'Great content, but could use more advanced examples.',
        date: '2024-01-08',
      },
    ],
  },
  {
    id: '2',
    title: 'Python for Data Science and Machine Learning',
    instructor: 'Sarah Davis',
    instructorImage: `https://i.pravatar.cc/40?img=2`,
    description: 'Learn Python programming for data science. Master pandas, numpy, matplotlib, and scikit-learn to build machine learning models.',
    shortDescription: 'Learn Python for data science and machine learning.',
    price: 94.99,
    originalPrice: 219.99,
    rating: 4.8,
    reviewCount: 2156,
    studentCount: 28750,
    image: `https://picsum.photos/400/250?random=2`,
    category: 'Data Science',
    subCategory: 'Python',
    level: 'Beginner',
    duration: '32 hours',
    language: 'English',
    lastUpdated: '2024-01-20',
    createdAt: '2023-11-15',
    whatYouWillLearn: [
      'Python programming fundamentals',
      'Data manipulation with pandas',
      'Data visualization with matplotlib',
      'Machine learning with scikit-learn',
    ],
    requirements: [
      'No prior programming experience required',
      'Basic math knowledge',
    ],
  },
  {
    id: '3',
    title: 'UI/UX Design Masterclass',
    instructor: 'Emily Chen',
    instructorImage: `https://i.pravatar.cc/40?img=3`,
    description: 'Complete guide to UI/UX design. Learn design principles, user research, wireframing, prototyping, and more.',
    shortDescription: 'Complete guide to UI/UX design principles and practices.',
    price: 79.99,
    originalPrice: 179.99,
    rating: 4.6,
    reviewCount: 987,
    studentCount: 12340,
    image: `https://picsum.photos/400/250?random=3`,
    category: 'Design',
    subCategory: 'UI/UX Design',
    level: 'Beginner',
    duration: '18 hours',
    language: 'English',
    lastUpdated: '2024-01-12',
    createdAt: '2023-10-20',
  },
  {
    id: '4',
    title: 'Full Stack Web Development with Next.js',
    instructor: 'Michael Brown',
    instructorImage: `https://i.pravatar.cc/40?img=4`,
    description: 'Build full-stack applications with Next.js, React, and Node.js. Learn server-side rendering, API routes, and database integration.',
    shortDescription: 'Build full-stack applications with Next.js and React.',
    price: 99.99,
    originalPrice: 229.99,
    rating: 4.9,
    reviewCount: 1876,
    studentCount: 22150,
    image: `https://picsum.photos/400/250?random=4`,
    category: 'Web Development',
    subCategory: 'Full Stack',
    level: 'Advanced',
    duration: '28 hours',
    language: 'English',
    lastUpdated: '2024-01-18',
    createdAt: '2023-12-10',
  },
  {
    id: '5',
    title: 'iOS App Development with Swift',
    instructor: 'David Wilson',
    instructorImage: `https://i.pravatar.cc/40?img=5`,
    description: 'Learn to build iOS apps from scratch using Swift and SwiftUI. Create beautiful, native iOS applications.',
    shortDescription: 'Learn to build iOS apps with Swift and SwiftUI.',
    price: 109.99,
    originalPrice: 249.99,
    rating: 4.7,
    reviewCount: 1456,
    studentCount: 18920,
    image: `https://picsum.photos/400/250?random=5`,
    category: 'Mobile Development',
    subCategory: 'iOS Development',
    level: 'Intermediate',
    duration: '26 hours',
    language: 'English',
    lastUpdated: '2024-01-14',
    createdAt: '2023-11-25',
  },
  {
    id: '6',
    title: 'Digital Marketing Complete Course',
    instructor: 'Lisa Anderson',
    instructorImage: `https://i.pravatar.cc/40?img=6`,
    description: 'Master digital marketing strategies including SEO, social media marketing, email marketing, and Google Ads.',
    shortDescription: 'Master digital marketing strategies and techniques.',
    price: 84.99,
    originalPrice: 199.99,
    rating: 4.5,
    reviewCount: 1123,
    studentCount: 14560,
    image: `https://picsum.photos/400/250?random=6`,
    category: 'Marketing',
    subCategory: 'Digital Marketing',
    level: 'Beginner',
    duration: '20 hours',
    language: 'English',
    lastUpdated: '2024-01-16',
    createdAt: '2023-12-05',
  },
  // Popular healthcare courses (Popular courses section)
  {
    id: 'hc1',
    title: 'CPHQ Preparation Course',
    instructor: 'IMETS Faculty',
    description: 'Comprehensive preparation for the Certified Professional in Healthcare Quality (CPHQ) examination.',
    shortDescription: 'CPHQ exam preparation course.',
    price: 11000,
    originalPrice: 10000,
    priceEGP: 11000,
    originalPriceEGP: 10000,
    rating: 4.8,
    reviewCount: 1340,
    studentCount: 3200,
    image: `https://picsum.photos/400/250?random=hc1`,
    category: 'Healthcare Quality',
    level: 'Intermediate',
    duration: '10 weeks',
    language: 'English',
    lastUpdated: '2024-01-15',
    isBestSeller: true,
    lectureCount: 10,
    lectureFrequency: '1 Lecture-Weekly',
    deliveryMode: 'Online-Zoom',
    popularFilter: 'Healthcare Quality',
    popularFilterTags: ['Doctors'],
  },
  {
    id: 'hc2',
    title: 'Healthcare Quality Management Diploma',
    instructor: 'IMETS Faculty',
    description: 'Diploma in Healthcare Quality Management for aspiring quality professionals.',
    shortDescription: 'Healthcare quality management diploma.',
    price: 15000,
    originalPrice: 24000,
    priceEGP: 15000,
    originalPriceEGP: 24000,
    rating: 4.7,
    reviewCount: 1800,
    studentCount: 1250,
    image: `https://picsum.photos/400/250?random=hc2`,
    category: 'Healthcare Management',
    level: 'Intermediate',
    duration: '17 weeks',
    language: 'English',
    lastUpdated: '2024-01-12',
    isBestSeller: false,
    lectureCount: 17,
    lectureFrequency: '1 Lecture-Weekly',
    deliveryMode: 'Online-Zoom',
    popularFilter: 'Healthcare Management',
  },
  {
    id: 'hc3',
    title: 'CIC Preparation Course',
    instructor: 'IMETS Faculty',
    description: 'Preparation for the Certification in Infection Control (CIC) examination.',
    shortDescription: 'CIC exam preparation course.',
    price: 11000,
    originalPrice: 10000,
    priceEGP: 11000,
    originalPriceEGP: 10000,
    rating: 4.8,
    reviewCount: 1100,
    studentCount: 1400,
    image: `https://picsum.photos/400/250?random=hc3`,
    category: 'Infection Control',
    level: 'Intermediate',
    duration: '12 weeks',
    language: 'English',
    lastUpdated: '2024-01-18',
    isBestSeller: true,
    lectureCount: 12,
    lectureFrequency: '1 Lecture-Weekly',
    deliveryMode: 'Online-Zoom',
    popularFilter: 'Infection Control',
    popularFilterTags: ['Doctors'],
  },
  {
    id: 'hc4',
    title: 'Infection Control Diploma',
    instructor: 'IMETS Faculty',
    description: 'Comprehensive diploma in infection prevention and control for healthcare settings.',
    shortDescription: 'Infection control diploma program.',
    price: 15000,
    originalPrice: 24000,
    priceEGP: 15000,
    originalPriceEGP: 24000,
    rating: 4.7,
    reviewCount: 1650,
    studentCount: 1750,
    image: `https://picsum.photos/400/250?random=hc4`,
    category: 'Infection Control',
    level: 'Intermediate',
    duration: '18 weeks',
    language: 'English',
    lastUpdated: '2024-01-10',
    isBestSeller: true,
    lectureCount: 18,
    lectureFrequency: '1 Lecture-Weekly',
    deliveryMode: 'Online-Zoom',
    popularFilter: 'Infection Control',
  },
  {
    id: 'hc5',
    title: 'Hospital Management Diploma',
    instructor: 'IMETS Faculty',
    description: 'Diploma in hospital and healthcare facility management.',
    shortDescription: 'Hospital management diploma.',
    price: 21000,
    originalPrice: 42000,
    priceEGP: 21000,
    originalPriceEGP: 42000,
    rating: 4.6,
    reviewCount: 980,
    studentCount: 1300,
    image: `https://picsum.photos/400/250?random=hc5`,
    category: 'Healthcare Management',
    level: 'Intermediate',
    duration: '42 weeks',
    language: 'English',
    lastUpdated: '2024-01-08',
    isBestSeller: true,
    lectureCount: 42,
    lectureFrequency: '1 Lecture-Weekly',
    deliveryMode: 'Online-Zoom',
    popularFilter: 'Healthcare Management',
  },
  {
    id: 'hc6',
    title: 'Healthcare Marketing Management Diploma',
    instructor: 'IMETS Faculty',
    description: 'Diploma in healthcare marketing and strategic communication.',
    shortDescription: 'Healthcare marketing management.',
    price: 8500,
    originalPrice: 17000,
    priceEGP: 8500,
    originalPriceEGP: 17000,
    rating: 4.5,
    reviewCount: 720,
    studentCount: 950,
    image: `https://picsum.photos/400/250?random=hc6`,
    category: 'Healthcare Management',
    level: 'Beginner',
    duration: '8 weeks',
    language: 'English',
    lastUpdated: '2024-01-14',
    isBestSeller: true,
    lectureCount: 8,
    lectureFrequency: '1 Lecture-Weekly',
    deliveryMode: 'Online-Zoom',
    popularFilter: 'Healthcare Management',
    popularFilterTags: ['Pharmacists'],
  },
  {
    id: 'hc7',
    title: 'Healthcare HR Management Diploma',
    instructor: 'IMETS Faculty',
    description: 'Diploma in human resources management for healthcare organizations.',
    shortDescription: 'Healthcare HR management.',
    price: 8500,
    originalPrice: 17000,
    priceEGP: 8500,
    originalPriceEGP: 17000,
    rating: 4.6,
    reviewCount: 890,
    studentCount: 1100,
    image: `https://picsum.photos/400/250?random=hc7`,
    category: 'Healthcare Management',
    level: 'Beginner',
    duration: '10 weeks',
    language: 'English',
    lastUpdated: '2024-01-11',
    isBestSeller: false,
    lectureCount: 10,
    lectureFrequency: '1 Lecture-Weekly',
    deliveryMode: 'Online-Zoom',
    popularFilter: 'Healthcare Management',
  },
  {
    id: 'hc8',
    title: 'Healthcare Strategic Management Diploma',
    instructor: 'IMETS Faculty',
    description: 'Diploma in strategic planning and management for healthcare leaders.',
    shortDescription: 'Healthcare strategic management.',
    price: 8500,
    originalPrice: 17000,
    priceEGP: 8500,
    originalPriceEGP: 17000,
    rating: 4.7,
    reviewCount: 1100,
    studentCount: 1450,
    image: `https://picsum.photos/400/250?random=hc8`,
    category: 'Healthcare Management',
    level: 'Intermediate',
    duration: '8 weeks',
    language: 'English',
    lastUpdated: '2024-01-16',
    isBestSeller: true,
    lectureCount: 8,
    lectureFrequency: '1 Lecture-Weekly',
    deliveryMode: 'Online-Zoom',
    popularFilter: 'Healthcare Management',
    popularFilterTags: ['Pharmacists'],
  },
  {
    id: 'hc9',
    title: 'Healthcare Supply Chain Management Diploma',
    instructor: 'IMETS Faculty',
    description: 'Diploma in supply chain and logistics management for healthcare.',
    shortDescription: 'Healthcare supply chain management.',
    price: 8500,
    originalPrice: 17000,
    priceEGP: 8500,
    originalPriceEGP: 17000,
    rating: 4.6,
    reviewCount: 950,
    studentCount: 1200,
    image: `https://picsum.photos/400/250?random=hc9`,
    category: 'Healthcare Management',
    level: 'Intermediate',
    duration: '10 weeks',
    language: 'English',
    lastUpdated: '2024-01-13',
    isBestSeller: true,
    lectureCount: 10,
    lectureFrequency: '1 Lecture-Weekly',
    deliveryMode: 'Online-Zoom',
    popularFilter: 'Healthcare Management',
  },
];

export const POPULAR_FILTER_TABS = ['All', 'Healthcare Quality', 'Infection Control', 'Healthcare Management', 'Doctors', 'Pharmacists'] as const;

/** URL slug from category name (e.g. "Web Development" → "web-development"). */
export function getCategorySlug(category: Category): string {
  return category.name.toLowerCase().replace(/\s+/g, "-");
}

/** Find category by id or by URL slug (from name). */
export function getCategoryBySlugOrId(slugOrId: string): Category | undefined {
  const byId = categories.find((c) => c.id === slugOrId);
  if (byId) return byId;
  const slugLower = slugOrId.toLowerCase();
  return categories.find((c) => getCategorySlug(c) === slugLower);
}

export function getPopularCourses(): Course[] {
  return courses.filter((c) => c.lectureCount != null && c.priceEGP != null);
}

export function getRelevantCourses(currentId: string, limit = 6): Course[] {
  const popular = getPopularCourses().filter((c) => c.id !== currentId);
  if (popular.length >= limit) return popular.slice(0, limit);
  const rest = courses.filter((c) => c.id !== currentId && !popular.some((p) => p.id === c.id));
  return [...popular, ...rest].slice(0, limit);
}
