import { Course, Category } from '@/types/course';

export const categories: Category[] = [
  { id: '1', name: 'Web Development', icon: '💻', courseCount: 245 },
  { id: '2', name: 'Data Science', icon: '📊', courseCount: 189 },
  { id: '3', name: 'Mobile Development', icon: '📱', courseCount: 156 },
  { id: '4', name: 'Design', icon: '🎨', courseCount: 203 },
  { id: '5', name: 'Business', icon: '💼', courseCount: 178 },
  { id: '6', name: 'Marketing', icon: '📈', courseCount: 134 },
  { id: '7', name: 'Photography', icon: '📷', courseCount: 98 },
  { id: '8', name: 'Music', icon: '🎵', courseCount: 87 },
];

export const courses: Course[] = [
  {
    id: '1',
    title: 'Complete React Development Bootcamp',
    instructor: 'John Smith',
    instructorImage: `https://i.pravatar.cc/40?img=1`,
    description: 'Master React from scratch. Build real-world projects and learn modern React patterns including hooks, context, and more.',
    shortDescription: 'Master React from scratch. Build real-world projects.',
    price: 89.99,
    originalPrice: 199.99,
    rating: 4.7,
    reviewCount: 1234,
    studentCount: 15420,
    image: `https://picsum.photos/400/250?random=1`,
    category: 'Web Development',
    level: 'Intermediate',
    duration: '24.5 hours',
    language: 'English',
    lastUpdated: '2024-01-15',
    whatYouWillLearn: [
      'Build modern React applications',
      'Understand React hooks and context',
      'Implement routing and state management',
      'Deploy React apps to production',
    ],
    requirements: [
      'Basic JavaScript knowledge',
      'HTML and CSS fundamentals',
      'A computer with internet connection',
    ],
    curriculum: [
      {
        id: '1',
        title: 'Getting Started',
        lectures: [
          { id: '1', title: 'Introduction to React', duration: '15:30', isPreview: true },
          { id: '2', title: 'Setting up your environment', duration: '12:45', isPreview: false },
        ],
      },
      {
        id: '2',
        title: 'React Fundamentals',
        lectures: [
          { id: '3', title: 'Components and Props', duration: '20:15', isPreview: false },
          { id: '4', title: 'State and Events', duration: '18:30', isPreview: true },
        ],
      },
    ],
    reviews: [
      {
        id: '1',
        userName: 'Alice Johnson',
        rating: 5,
        comment: 'Excellent course! Very comprehensive and well-structured.',
        date: '2024-01-10',
      },
      {
        id: '2',
        userName: 'Bob Williams',
        rating: 4,
        comment: 'Great content, but could use more advanced examples.',
        date: '2024-01-08',
      },
    ],
  },
  {
    id: '2',
    title: 'Python for Data Science and Machine Learning',
    instructor: 'Sarah Davis',
    instructorImage: `https://i.pravatar.cc/40?img=2`,
    description: 'Learn Python programming for data science. Master pandas, numpy, matplotlib, and scikit-learn to build machine learning models.',
    shortDescription: 'Learn Python for data science and machine learning.',
    price: 94.99,
    originalPrice: 219.99,
    rating: 4.8,
    reviewCount: 2156,
    studentCount: 28750,
    image: `https://picsum.photos/400/250?random=2`,
    category: 'Data Science',
    level: 'Beginner',
    duration: '32 hours',
    language: 'English',
    lastUpdated: '2024-01-20',
    whatYouWillLearn: [
      'Python programming fundamentals',
      'Data manipulation with pandas',
      'Data visualization with matplotlib',
      'Machine learning with scikit-learn',
    ],
    requirements: [
      'No prior programming experience required',
      'Basic math knowledge',
    ],
  },
  {
    id: '3',
    title: 'UI/UX Design Masterclass',
    instructor: 'Emily Chen',
    instructorImage: `https://i.pravatar.cc/40?img=3`,
    description: 'Complete guide to UI/UX design. Learn design principles, user research, wireframing, prototyping, and more.',
    shortDescription: 'Complete guide to UI/UX design principles and practices.',
    price: 79.99,
    originalPrice: 179.99,
    rating: 4.6,
    reviewCount: 987,
    studentCount: 12340,
    image: `https://picsum.photos/400/250?random=3`,
    category: 'Design',
    level: 'Beginner',
    duration: '18 hours',
    language: 'English',
    lastUpdated: '2024-01-12',
  },
  {
    id: '4',
    title: 'Full Stack Web Development with Next.js',
    instructor: 'Michael Brown',
    instructorImage: `https://i.pravatar.cc/40?img=4`,
    description: 'Build full-stack applications with Next.js, React, and Node.js. Learn server-side rendering, API routes, and database integration.',
    shortDescription: 'Build full-stack applications with Next.js and React.',
    price: 99.99,
    originalPrice: 229.99,
    rating: 4.9,
    reviewCount: 1876,
    studentCount: 22150,
    image: `https://picsum.photos/400/250?random=4`,
    category: 'Web Development',
    level: 'Advanced',
    duration: '28 hours',
    language: 'English',
    lastUpdated: '2024-01-18',
  },
  {
    id: '5',
    title: 'iOS App Development with Swift',
    instructor: 'David Wilson',
    instructorImage: `https://i.pravatar.cc/40?img=5`,
    description: 'Learn to build iOS apps from scratch using Swift and SwiftUI. Create beautiful, native iOS applications.',
    shortDescription: 'Learn to build iOS apps with Swift and SwiftUI.',
    price: 109.99,
    originalPrice: 249.99,
    rating: 4.7,
    reviewCount: 1456,
    studentCount: 18920,
    image: `https://picsum.photos/400/250?random=5`,
    category: 'Mobile Development',
    level: 'Intermediate',
    duration: '26 hours',
    language: 'English',
    lastUpdated: '2024-01-14',
  },
  {
    id: '6',
    title: 'Digital Marketing Complete Course',
    instructor: 'Lisa Anderson',
    instructorImage: `https://i.pravatar.cc/40?img=6`,
    description: 'Master digital marketing strategies including SEO, social media marketing, email marketing, and Google Ads.',
    shortDescription: 'Master digital marketing strategies and techniques.',
    price: 84.99,
    originalPrice: 199.99,
    rating: 4.5,
    reviewCount: 1123,
    studentCount: 14560,
    image: `https://picsum.photos/400/250?random=6`,
    category: 'Marketing',
    level: 'Beginner',
    duration: '20 hours',
    language: 'English',
    lastUpdated: '2024-01-16',
  },
];
