import { Event } from '@/types/event';

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Web Development Workshop',
    description: 'A comprehensive workshop covering modern web development practices and tools.',
    startDate: '2024-02-15',
    endDate: '2024-02-15',
    startTime: '10:00',
    endTime: '16:00',
    location: 'Tech Hub, Downtown',
    isOnline: false,
    category: 'Workshop',
    maxAttendees: 50,
    currentAttendees: 32,
    price: 99.99,
    status: 'published',
    createdAt: '2024-01-10',
    updatedAt: '2024-01-20',
  },
  {
    id: '2',
    title: 'Online React Masterclass',
    description: 'Learn advanced React patterns and best practices in this interactive online session.',
    startDate: '2024-02-20',
    endDate: '2024-02-20',
    startTime: '14:00',
    endTime: '18:00',
    isOnline: true,
    meetingLink: 'https://meet.example.com/react-masterclass',
    category: 'Masterclass',
    maxAttendees: 100,
    currentAttendees: 67,
    price: 149.99,
    status: 'published',
    createdAt: '2024-01-12',
    updatedAt: '2024-01-18',
  },
  {
    id: '3',
    title: 'Data Science Bootcamp',
    description: 'Intensive 3-day bootcamp on data science fundamentals and machine learning.',
    startDate: '2024-03-01',
    endDate: '2024-03-03',
    startTime: '09:00',
    endTime: '17:00',
    location: 'Conference Center',
    isOnline: false,
    category: 'Bootcamp',
    maxAttendees: 30,
    currentAttendees: 15,
    price: 299.99,
    status: 'draft',
    createdAt: '2024-01-15',
    updatedAt: '2024-01-22',
  },
];
