import { Quiz } from '@/types/quiz';

export const mockQuizzes: Quiz[] = [
  {
    id: '1',
    title: 'React Fundamentals Quiz',
    description: 'Test your knowledge of React basics',
    courseId: '1',
    courseName: 'Complete React Development Bootcamp',
    duration: 30,
    passingScore: 70,
    maxAttempts: 3,
    isPublished: true,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-20',
    questions: [
      {
        id: 'q1',
        quizId: '1',
        questionText: 'What is React?',
        questionType: 'multiple-choice',
        options: [
          'A JavaScript library for building user interfaces',
          'A database management system',
          'A CSS framework',
          'A server-side framework',
        ],
        correctAnswer: 'A JavaScript library for building user interfaces',
        points: 10,
        explanation: 'React is a JavaScript library developed by Facebook for building user interfaces.',
        order: 1,
      },
      {
        id: 'q2',
        quizId: '1',
        questionText: 'React uses a virtual DOM.',
        questionType: 'true-false',
        correctAnswer: 'true',
        points: 5,
        explanation: 'React uses a virtual DOM to optimize rendering performance.',
        order: 2,
      },
    ],
  },
  {
    id: '2',
    title: 'Python Basics Assessment',
    description: 'Evaluate your Python programming skills',
    courseId: '2',
    courseName: 'Python for Data Science and Machine Learning',
    duration: 45,
    passingScore: 75,
    maxAttempts: 2,
    isPublished: true,
    createdAt: '2024-01-18',
    updatedAt: '2024-01-22',
    questions: [],
  },
];
